
#azure.keyvault.tenant.id=ff399ab6-51c4-4516-9115-509005857a64
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://example.net/

spring.datasource.url=jdbc:mysql://${DB-HOST}:${DB-PORT}/${DB-NAME}?useSSL=true&requireSSL=true
spring.datasource.username=${DB-USER}
spring.datasource.password=${DB-PASSWORD}

spring.jpa.show-sql = false
spring.jpa.properties.hibernate.format_sql = false

server.error.include-stacktrace = never

api.security.token.secret = ${API-KEY}
